CREATE DATABASE SISTEMA_AUTOBUS
USE SISTEMA_AUTOBUS
GO
CREATE TABLE CHOFER(
ID_CHOFER INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (40),
APELLIDO VARCHAR (40),
FECHA VARCHAR (20),
CEDULA VARCHAR(15),
DISPO VARCHAR(4)DEFAULT 'V'
)

CREATE TABLE AUTOBUS(
ID_AUTOBUS INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
MARCA  VARCHAR (30),
MODELO VARCHAR (30),
PLACA  VARCHAR (30),
COLOR  VARCHAR (30),
AGE    VARCHAR (30),
DISPO VARCHAR(4)DEFAULT 'V'
)

CREATE TABLE RUTA (
ID_RUTA INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (40),
DISPO VARCHAR(4)DEFAULT 'V'
)

CREATE TABLE VIAJE (
ID_VIAJE INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
CHOFER VARCHAR (30),
AUTOBUS VARCHAR (30),
RUTA VARCHAR (30),
)

 --PROCESO DEL CRUD--
 /*CRUD PARA CHOFER*/
 GO
 --INSERTAR CHOFER--
 CREATE PROC SP_INSERTARCHOFER
@NOMBRE VARCHAR (40),
@APELLIDO VARCHAR (40),
@FECHA VARCHAR (30),
@CEDULA VARCHAR (15)
AS
INSERT INTO CHOFER(NOMBRE,APELLIDO,FECHA,CEDULA) VALUES (@NOMBRE,@APELLIDO,@FECHA,@CEDULA)

--EDITAR CHOFER--
GO
CREATE PROC SP_EDITARCHOFER
@ID_CHOFER INT,
@NOMBRE VARCHAR(40),
@APELLIDO VARCHAR (40),
@FECHA VARCHAR (30),
@CEDULA VARCHAR (15)
AS
UPDATE CHOFER SET NOMBRE =@NOMBRE, APELLIDO =@APELLIDO, FECHA=@FECHA, CEDULA=@CEDULA
WHERE ID_CHOFER=@ID_CHOFER

--ELIMINAR CHOFER--
GO
CREATE PROC SP_ELIMINARCHOFER
@ID_CHOFER INT
AS
DELETE CHOFER
WHERE ID_CHOFER =@ID_CHOFER

--BUSCAR CHOFER--
GO
CREATE PROC SP_BUSCARCHOFER
@BUSCAR NVARCHAR (20)
AS
SELECT *FROM CHOFER
WHERE NOMBRE LIKE @BUSCAR +'%'

/*CRUD PARA AUTOBUS*/
 GO
 --INSERTAR AUTOBUS--
 CREATE PROC SP_INSERTARAUTOBUS
@MARCA VARCHAR (40),
@MODELO VARCHAR (40),
@PLACA VARCHAR (30),
@COLOR VARCHAR (15),
@AGE VARCHAR (30)
AS
INSERT INTO AUTOBUS(MARCA,MODELO,PLACA,COLOR, AGE ) VALUES (@MARCA,@MODELO,@PLACA,@COLOR,@AGE)

--EDITAR AUTOBUS--
GO
CREATE PROC SP_EDITARAUTOBUS
@ID_AUTOBUS INT,
@MARCA VARCHAR (40),
@MODELO VARCHAR (40),
@PLACA VARCHAR (30),
@COLOR VARCHAR (15),
@AGE VARCHAR (30)
AS
UPDATE AUTOBUS SET  MARCA= @MARCA, MODELO =@MODELO,PLACA=@PLACA, COLOR=@COLOR,AGE=@AGE
WHERE ID_AUTOBUS= @ID_AUTOBUS

--ELIMINAR AUTOBUS--
GO
CREATE PROC SP_ELIMINARAUTOBUS
@ID_AUTOBUS INT
AS
DELETE AUTOBUS
WHERE ID_AUTOBUS =@ID_AUTOBUS

--BUSCAR AUTOBUS--
GO
CREATE PROC SP_BUSCARAUTOBUS
@BUSCAR NVARCHAR (20)
AS
SELECT *FROM AUTOBUS
WHERE PLACA LIKE @BUSCAR +'%'

/*CRUD PARA RUTA*/
 GO
 --INSERTAR RUTA--
 CREATE PROC SP_INSERTARRUTA
@NOMBRE VARCHAR (40)
AS
INSERT INTO RUTA (NOMBRE)VALUES (@NOMBRE)

--EDITAR RUTA-
GO
CREATE PROC SP_EDITARRUTA
@ID_RUTA INT,
@NOMBRE VARCHAR(40)
AS
UPDATE RUTA SET NOMBRE =@NOMBRE
WHERE ID_RUTA=@ID_RUTA

--ELIMINAR RUTA--
GO
CREATE PROC SP_ELIMINARRUTA
@ID_RUTA INT
AS
DELETE RUTA
WHERE ID_RUTA =@ID_RUTA

--BUSCAR RUTA--
GO
CREATE PROC SP_BUSCARRUTA
@BUSCAR NVARCHAR (20)
AS
SELECT *FROM RUTA
WHERE NOMBRE LIKE @BUSCAR +'%'



--PROCESO DE INICIAR--
--CARGAR CB CHOFER--
GO
CREATE PROC SP_CARGARCHOFER
AS
SELECT
   NOMBRE
FROM
CHOFER
WHERE 
DISPO='V'
--CARGAR CB AUTOBUS--
GO
CREATE PROC SP_CARGARAUTOBUS
AS
SELECT PLACA,
 CONCAT (MARCA,'',MODELO) AUTOBUS
FROM
AUTOBUS
WHERE 
DISPO='V'

--CARGAR RUTA --
GO
CREATE PROC SP_CARGARRUTA
AS
SELECT 
NOMBRE AS RUTA
FROM RUTA
WHERE 
DISPO='V'


DROP PROC SP_CARGARCHOFER
exec SP_CARGARRUTA

--BUSCAR VIAJE--
GO
 --INSERTAR VIAJE--
 CREATE PROC SP_INSERTARVIAJE
@CHOFER VARCHAR (40),
@AUTOBUS VARCHAR (40),
@RUTA VARCHAR (30)
AS
INSERT INTO VIAJE(CHOFER,AUTOBUS,RUTA) VALUES (@CHOFER,@AUTOBUS,@RUTA)
GO
CREATE PROC SP_DISPO_CHOFER
@NOMBRE VARCHAR (30)
AS
UPDATE CHOFER SET DISPO ='F' WHERE NOMBRE =@NOMBRE
GO
CREATE PROC SP_DISPO_AUTOBUS
@PLACA VARCHAR (30)
AS
UPDATE AUTOBUS SET DISPO='F' WHERE PLACA =@PLACA
GO
CREATE PROC SP_DISPO_RUTA
@RUTA VARCHAR (30)
AS
UPDATE RUTA SET DISPO='F' WHERE NOMBRE =@RUTA
-------------------------------------------------------------
GO
CREATE PROC SP_DISPO_CHOFER_V
@NOMBRE VARCHAR (30)
AS
UPDATE CHOFER SET DISPO ='V' WHERE NOMBRE =@NOMBRE
GO
CREATE PROC SP_DISPO_AUTOBUS_V
@PLACA VARCHAR (30)
AS
UPDATE AUTOBUS SET DISPO='V' WHERE PLACA =@PLACA
GO
CREATE PROC SP_DISPO_RUTA_V
@RUTA VARCHAR (30)
AS
UPDATE RUTA SET DISPO='V' WHERE NOMBRE =@RUTA
GO
CREATE PROC SP_FINALIZAR_VIAJE
@ID_VIAJE INT
AS
DELETE FROM VIAJE WHERE ID_VIAJE=@ID_VIAJE
DROP TABLE RUTA
GO
SELECT * FROM CHOFER
SELECT * FROM AUTOBUS
SELECT * FROM RUTA
-----INSERT PRUEBA

INSERT INTO CHOFER VALUES('PAIQUER', 'ORTIZ', '1994-03-11', '402-14234518-9')

INSERT INTO AUTOBUS VALUES('HONDA', 'H-2000', 'RD-1237651', 'ROJO', '2003')

INSERT INTO RUTA VALUES('AV.CORALES')